# GitHub Pages configuration
title: 株式会社スパイスエンジン
description: 世界最速のAI基盤を創出する - AIハードウェアアクセラレータ開発
baseurl: ""
url: "https://spiceengine.github.io"

# Build settings
markdown: kramdown
theme: minima
highlighter: rouge

# Blog settings
paginate: 5
paginate_path: "/blog/page:num/"

# Exclude files from processing
exclude:
  - README.md
  - claude-prompt.txt
  - process_logo.py
  - venv/
  - .gitignore
  - server.log

# Permalink settings
permalink: pretty

# Default values
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
      author: "SpiceEngine"

# Blog configuration
blog:
  title: "SpiceEngine Tech Blog"
  description: "AIハードウェアアクセラレーション技術の最前線"