name: Agent
on:
  issues:                      { types: [opened, assigned, edited] }
  issue_comment:               { types: [created, edited] }
  pull_request:                { types: [opened, edited] }
  pull_request_review:         { types: [submitted] }
  pull_request_review_comment: { types: [created, edited] }
concurrency:
  group: ai-assistant-${{ github.event.issue.number || github.event.pull_request.number }}
  cancel-in-progress: true
jobs:
  claude:
    runs-on: self-hosted
    permissions: { contents: write, pull-requests: write, issues: write}
    steps:
    - uses: actions/checkout@v4
    - uses: spiceengine/action@main
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
