name: SpikyBot Code Agent
on: [issues, issue_comment, pull_request, pull_request_review, pull_request_review_comment]
concurrency:
  group: spikybot-${{ github.actor }}-${{ github.event.issue.number || github.event.pull_request.number }}
  cancel-in-progress: true
jobs:
  spiceengine-action:
    runs-on: self-hosted
    permissions: write-all
    steps:
    - uses: actions/checkout@v4
    - uses: spikybot/spikybot@main
      with:
        redis-url: ${{ secrets.REDIS_URL }}
        redis-token: ${{ secrets.REDIS_TOKEN }}
